### ISSUE TITLE
Parameter "Only one perimeter on Top surfaces" produces not wanted artifacts

### ISSUE THREAD

**Issue by Panayiotis-git** [supermerill/Slic3r#111]
### Version
 2.1.44.0

### Operating system type + version
Windows 7 64-bit

### 3D printer brand / version + firmware version (if known)
i3 MK3S

### Behavior
The parameter "Only one perimeter on Top surfaces", when set, produces artifact to the previous layer of perimeters.

For the following stl file:
![image](https://user-images.githubusercontent.com/32783577/67894715-cb235280-fb61-11e9-8bb4-f1aeafafd8ca.png)

When the parameter "Only one perimeter on Top surfaces" is set, the first layer is:
![image](https://user-images.githubusercontent.com/32783577/67894792-f7d76a00-fb61-11e9-999c-9e641f68c7ee.png)

When the parameter is not selected, the first layer is calculated correctly:
![image](https://user-images.githubusercontent.com/32783577/67894821-06be1c80-fb62-11e9-8d4b-2c11c7a0244b.png)

#### Project File (.3MF) where problem occurs
[test1.zip](https://github.com/supermerill/Slic3r/files/3790963/test1.zip)

**Comment by supermerill** [comment]
That's because the yellow perimeter have to be pushed to the inner part to not be on top.

Do you want only one perimeter on the top surface, or not?

If you really want one perimeter for all surfaces (even the inner one) on the first layer, you have to use a modifier with the "perimeters" setting to 1.
