### ISSUE TITLE
Support for no top layer under features

### ISSUE THREAD

**Issue by Coffee0297** [supermerill/Slic3r#169]
so i have this model 
![image](https://user-images.githubusercontent.com/43273303/75072893-ad0aa500-54f8-11ea-93ea-eb3406525a72.png)
and it prints the top layer and then the feature? is this intented? 
it dont seem great for layerbondig and general structure of the part.

![image](https://user-images.githubusercontent.com/43273303/75072982-d7f4f900-54f8-11ea-9775-826396ca94f8.png)

None of the briging settings or the 1 perimeter did solve it.

-Tonny

**Comment by supermerill** [comment]
If your problem is that it doesn't create a perimeter in the middle of the second picture, it shouldn't be a problem. If the bonding isn't good, it's because there is a lack of plastic -> you can look to up the over-bridge flow a bit.

If you really really want perimeters just below the "feature", put "0" under "infill->anchor solid infill by X mm: -> Default"
