### ISSUE TITLE
Slicing issue when using modifier for infill

### ISSUE THREAD

**Issue by make92** [supermerill/Slic3r#201]
### Version
2.2.48

### Operating system type + version
Windows 10

### 3D printer brand / version + firmware version (if known)
_What 3D printer brand / version are you printing on, is it a stock model or did you modify the printer, what firmware is running on your printer, version of the firmware #s_

### Behavior
when adding a modifier for the upper part of a model to change the infill to 100% for example
its loosing all perimeter for the part below the modivier.

![image](https://user-images.githubusercontent.com/15849843/79696600-ebfd7280-827d-11ea-9804-9d0454b8ee19.png)

![image](https://user-images.githubusercontent.com/15849843/79696526-814c3700-827d-11ea-97f0-59b6a99476b5.png)

**Comment by supermerill** [comment]
in the meantime, you can add the "perimeter count" in the modifier to make it work.

**Comment by make92** [comment]
> perimeter count

ok will do that, thanks a lot

**Comment by liftbag** [comment]
<img width="1532" alt="Schermata 2020-04-26 alle 15 01 15" src="https://user-images.githubusercontent.com/14921654/80308585-201de980-87d0-11ea-887b-ebc4d0048595.png">


I confirm the issue. I cannot try the #201 nightly build on macOS, because the executable is damaged.

<img width="663" alt="Schermata 2020-04-26 alle 15 10 02" src="https://user-images.githubusercontent.com/14921654/80308598-2d3ad880-87d0-11ea-9421-23f9b2449181.png">


<img width="663" alt="Schermata 2020-04-26 alle 15 10 25" src="https://user-images.githubusercontent.com/14921654/80308594-290ebb00-87d0-11ea-8a69-ab76cd474e27.png">

**Comment by supermerill** [comment]
Fix should be in the 201 build.
You try to execute the .dmg or from the tar archive?

**Comment by liftbag** [comment]
> @liftbag Fix should be in the 201 build.
> You try to execute the .dmg or from the tar archive?
> I don't have a mac so i can't test them. I
> even don't know how you use them.

From .dmg. I'll try from the tar.

**Comment by make92** [comment]
the latest version fixed the problem for me.
thanks a lot.

**Comment by liftbag** [comment]
I got to try the release on windows, and I confirm that it works. But the application for macOS, to which the latest release refers, is damaged.

**Comment by supermerill** [comment]
I understand, but i can't 'repair' it on my own, as i don't know why/what is "damaged".
