### ISSUE TITLE
first_layer_print_min and first_layer_print_max not working in [Beta 2.4.58.0]

### ISSUE THREAD

**Issue by kejar31** [supermerill/Slic3r#2381]
### What happened?

When trying to pull the print size for adaptive bed mesh I am getting a return of 0 for first_layer_print_min and first_layer_print_max

### Project file & How to reproduce

add 

SIZE={first_layer_print_min[0]}_{first_layer_print_min[1]}_{first_layer_print_max[0]}_{first_layer_print_max[1]} 

to your print_start gcode

It should return something like this (SIZE=131.731_134.731_162.269_165.269) but instead I am getting (SIZE=0_0_0_0)

### Version

2.4.58.0

### Operating system

Windows 10

### Printer model

voron 2.4

**Comment by supermerill** [comment]
seems like the first_layer_convex_hull is no more computed...

**Comment by ascii-ts** [comment]
i'm running Version 2.4.58.2 and the issue is there.
i just started using superslicer. i'm currently migrating away from cura.
i can see it is calculating. but looks like only 1 value.
this is part of my startcode
`;BED_MESH_CALIBRATE AREA_START={first_layer_print_min[0]},{first_layer_print_min[1]} AREA_END={first_layer_print_max[0]},{first_layer_print_max[1]}`
i just placed the box in the middle of the buildplate
the result in the gcode file is
`;BED_MESH_CALIBRATE AREA_START=128.284,128.284 AREA_END=171.716,171.716
`

**Comment by supermerill** [comment]
@ascii-ts 
just tested with a Rectangular cuboid near the origin:
`;BED_MESH_CALIBRATE AREA_START=11.698,14.3512 AREA_END=101.071,47.7181`

**Comment by ascii-ts** [comment]
@supermerill  well i just used the one which superslicer provides.
right click on build plat and add the shape  box.

the cylinder from the shape menu also gives me just 1 set of coordinates.

i just took a file from thingiverse and and added it to the build plate. https://www.thingiverse.com/thing:5310943
![image](https://user-images.githubusercontent.com/45358274/162370913-484e86c0-0c15-4dcd-88ee-90057a57d621.png)
the result was this
`;BED_MESH_CALIBRATE AREA_START=51.049,59.7822 AREA_END=248.949,240.218`
