### ISSUE TITLE
Feature Request: 3DConnextion Space Mouse support

### ISSUE THREAD

**Issue by LaserBee** [supermerill/Slic3r#41]
### Operating system type + version
Windows 10

_Is this a new feature request?_

Yes

Many people who do 3D design use a 3DConnextion Space Mouse. This tool works brilliant in things like Fusion360 and Blender, for navigating around a model, zooming, panning, &c. 

It would be helpful to have it work in Slic3r, too. It's not a major thing, but it would mean my work-flow between the design and the slicing would be improved!

Thanks for the consideration.

**Comment by supermerill** [comment]
It's for the camera mouvement (rotation/translation)?

**Comment by LaserBee** [comment]
Yes, exactly. Rotation, panning, zooming. It's not a mouse, really, you use
it *with* a mouse in the other hand.

**Comment by supermerill** [comment]
Most of the gui stuff is work-in-progress by Prusa research, so it may change quickly month after month.
Also, i don't want to tinker it because it's really boring and error-prone coding.
Also i don't have this sort of mouse.

Sorry, but this has a really really low priority for me, (taking weeks of free time for something I can't use...)
I can accept a pull request, but i can't do the code.

**Comment by supermerill** [comment]
seems like prusa is working on that.
So you'll be able to use your mouse with the next version of prusaslicer / when i'll merge it here.
